version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  web:
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
    ports:
      - 5000:5000
    links:
      - db
    environment:
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGHOST=db
      - FLASK_ENV=development
      - FLASK_APP=tracker.py
      - SECRET_KEY=blah
      - PRICE_API_KEY
    command: /bin/bash -c "python3 -m seeds.test; flask run --host 0.0.0.0"
  test:
    build:
      context: .
      dockerfile: dockerfiles/test.Dockerfile
    links:
      - web
    environment:
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGHOST=db
      - WEBHOST=web
      - FLASK_APP=tracker.py
      - SECRET_KEY=blah
      - PRICE_API_KEY
