version: '3'
services:
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'

  web:
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
    ports:
      - 5000:5000
    links:
      - db

  test:
    build:
      context: .
      dockerfile: dockerfiles/test.Dockerfile
    links:
      - web
