version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and run services
          command: |
            docker-compose up -d --build web db
      - run:
          name: Run tests
          command: |
            docker-compose up --build --exit-code-from test test


workflows:
  version: 2.1
  build_and_push_image_dev:
    jobs:
      - build-and-test:
        branches:
          ignore:
            - master
