version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1
  gcp-gke: circleci/gcp-gke@1.0.4

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and run services.  Run test suite
          command: |
            docker-compose up --build --exit-code-from test

  deploy-gke:
    executor: gcp-gke/default
    working_directory: ~/repo
    steps:
      - checkout
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: crypto-tracker-cluster
          perform-login: true
      - run:
          name: Append image number
          command: |
            sed -i 's/{{pipeline_number}}/<< pipeline.number >>/g' k8/deployment.yml
      - run:
          name: Apply K8s yml
          command: |
            kubectl apply -f k8


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - master

  deploy:
    jobs:
      - approve-deploy:
          type: approval
          filters:
            branches:
              only:
                - master
      - gcp-gcr/build-and-push-image:
          dockerfile: dockerfiles/app.Dockerfile
          image: crypto-api
          registry-url: eu.gcr.io
          tag: build<< pipeline.number >>
          requires:
            - approve-deploy
      - deploy-gke:
          requires:
            - gcp-gcr/build-and-push-image
