apiVersion: v1
kind: Service
metadata:
  name: crypto-api
  labels:
    app: crypto-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: null
  selector:
    app: crypto-api
