"""Currencies and re-index

Revision ID: cd8cd57c6a9e
Revises: d879b3f7359c
Create Date: 2020-04-04 16:16:50.056048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd8cd57c6a9e'
down_revision = 'd879b3f7359c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('cd', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('cd')
    )
    op.add_column('transaction', sa.Column('buy_amount', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('transaction', sa.Column('sell_amount', sa.Float(), nullable=True))
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.drop_index('ix_transaction_trans_ts', table_name='transaction')
    op.drop_column('transaction', 'trans_ts')
    op.drop_column('transaction', 'sell_amt')
    op.drop_column('transaction', 'buy_amt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('buy_amt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('sell_amt', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('trans_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_transaction_trans_ts', 'transaction', ['trans_ts'], unique=False)
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_column('transaction', 'sell_amount')
    op.drop_column('transaction', 'date')
    op.drop_column('transaction', 'buy_amount')
    op.drop_table('currency')
    # ### end Alembic commands ###
