"""transactions table

Revision ID: d879b3f7359c
Revises: bd0e6dafe4b7
Create Date: 2020-03-26 19:53:16.987894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd879b3f7359c'
down_revision = 'bd0e6dafe4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_currency', sa.String(length=3), nullable=True),
    sa.Column('buy_amt', sa.Float(), nullable=True),
    sa.Column('sell_currency', sa.String(length=3), nullable=True),
    sa.Column('sell_amt', sa.Float(), nullable=True),
    sa.Column('trans_ts', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_trans_ts'), 'transaction', ['trans_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_trans_ts'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
